const images = {
  // back: require('../../assets/images/back.png'),
  // checkBoxOn: require('../../assets/images/checkbox_on.png'),
  // checkBoxOff: require('../../assets/images/checkbox_off.png'),
  // close: require('../../assets/images/close.png'),
  // dropdown: require('../../assets/images/ic_dropdown.png'),
  // faceSad: require('../../assets/images/face_sad.svg'),
  // login: require('../../assets/images/login.png'),
  // modalCamera: require('../../assets/images/modal_camera.png'),
  // modalGallery: require('../../assets/images/modal_gallery.png'),
  // noConnection: require('../../assets/images/no_connection.png'),
  // onBoarding: [
  //   require('../../assets/images/onBoarding_0.png'),
  //   require('../../assets/images/onBoarding_1.jpg'),
  //   require('../../assets/images/onBoarding_2.png')
  // ],
  // passOff: require('../../assets/images/padlock_off.png'),
  // passOn: require('../../assets/images/padlock_on.png'),
  // search: require('../../assets/images/ic_search.png'),
  // userOff: require('../../assets/images/user_off.png'),
  // userOn: require('../../assets/images/user_on.png'),
  appLogo: require('../image/logo.png'),
  smallAppLogo: require('../image/smallLogo.png'),
  testIcon: require('../image/test.png'),
  thumnail: require('../image/thumnail.png'),
  batik: require('../image/batik.png'),
  profile: require('../image/profile.png'),
  garuda: require('../image/garuda.jpg'),
  gentongan: require('../image/gentongan.jpg'),
  jepara: require('../image/jepara.jpg'),
  kawung: require('../image/kawung.jpg'),
  keraton: require('../image/keraton.jpg'),
  megaMendung: require('../image/megamendung.jpg'),
  parang: require('../image/parang.jpg'),
  pringSedapur: require('../image/pringsedapur.jpg'),
  priyangan: require('../image/priangan.jpg'),
  simbut: require('../image/simbut.jpg'),
  sogan: require('../image/sogan.jpg'),
  tujuhRupa: require('../image/tujuhrupa.jpg'),
  tulis: require('../image/btulis.jpg'),
  cap: require('../image/bcap.jpg'),
  print: require('../image/bprint.jpg'),
  headerBgImg: require('../image/headerBg.png'),
  setting: require('../image/setting.png'),
  profil: require('../image/profil.png'),
  rz: require('../image/about1.png'),
  zuh: require('../image/about2.png'),
  div: require('../image/about3.png'),
  rat: require('../image/about4.png'),
  mar: require('../image/about5.png'),
  bImage: require('../image/bimage.png'),
  berita1: require('../image/berita1.png'),
  berita2: require('../image/berita2.png'),
  galeri1: require('../image/gallery/garuda.png'),
  galeri2: require('../image/gallery/gentongan.png'),
  galeri3: require('../image/gallery/jepara.png'),
  galeri4: require('../image/gallery/kawung.png'),
  galeri5: require('../image/gallery/keraton.png'),
  galeri6: require('../image/gallery/mega.png'),
  galeri7: require('../image/gallery/parang.png'),
  galeri8: require('../image/gallery/pringsedapur.png'),
  galeri9: require('../image/gallery/simbut.png'),
  galeri10: require('../image/gallery/sogan.png'),
  galeri11: require('../image/gallery/tujuh.png'),
  galeri12: require('../image/gallery/priangan.png'),
  pattern: require('../image/pattern.png'),
};

export default images;
